### ISSUE TITLE
How to use patch?

### ISSUE THREAD

**Issue by steventanwc** [feathersjs-ecosystem/feathers-batch#33]
Hi

Thank you for the wonderful module. I am able to use the find, create, delete

But can you show me how to do patch?

I have tried many variations:

{
  "type": "parallel",
  "call": [
    [ "products::patch", { "id": 9 , "favouriteStatus": true} ]
  ]
}

but can't get it working

Thanks

**Comment by daffl** [comment]
Should be the same as for `update`:

```
{
"type": "parallel",
"call": [
[ "products::patch", 9, { "favouriteStatus": true } ]
]
}
```
