### ISSUE TITLE
Does not work with Feathers v3.x - because callbacks

### ISSUE THREAD

**Issue by tuddman** [feathersjs-ecosystem/feathers-batch#36]
### Expected behavior

attempted to use this batch library with feathers `3.0.2` and be able to make batch calls.

### Actual behavior

errors, errors, everywhere.  because callbacks.

**Comment by daffl** [comment]
Indeed. A few Ecosystem plugins are not compatible yet with latest. This one needed some love for a while (like the promise updates and a batch call client).

**Comment by jcarty** [comment]
Any update on this?

Thanks!

**Comment by NikitaVlaznev** [comment]
@daffl, is there any blockers for the release?

**Comment by daffl** [comment]
Closed via #39
