### ISSUE TITLE
Update README to warn of caveats 

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs-ecosystem/feathers-batch#66]
We should probably update the README to warn the user of some caveats of batching service calls on the server. Mainly, hooks that rely on `context.params.provider` will act differently. For example, I believe the current example in the README will leak the user's password.

```js
const [ user, messages ] = await Promise.all([
  client.service('users').get(userId),
  client.service('messages').find({
    query: { userId }
  })
]);

// Because the default `protect` hook does not protect on internal calls, the user's PW
// will be available here.
console.log(user.password);
```

Additionally, we may want to add something that sets the `context.params.provider = rest|socket|undefined` based on the parent batch service's provider to be "secure by default". There is some documentation around Authenticating only once in the parent batch service, and then actually relying on provider to be undefined for those subsequent calls which will not auth because provider is undefined. And that works and is great...and would break if we started passing provider around. With that said,  "param drilling" (aka passing provider, user, auth to nested/batched services) is also dangerous and a pain, so that may not be a great solution either.

I am happy to open a PR where we just document this, but wanted to get some feedback first.

**Comment by daffl** [comment]
It merges the params (https://github.com/feathersjs-ecosystem/feathers-batch/blob/release/lib/index.js#L23) and passes them along to each service call. It'll basically look the same as if it was made externally.

**Comment by DaddyWarbucks** [comment]
Sure does! Sorry about that!
I was just perusing the README and noted the Authentication bit. Now I understand the auth is skipped on those batched services because the auth params exist, not necessarily because the provider is undefined. I should have read the code more thoroughly before opening an issue.
